apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksubscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksubscriber
  template:
    metadata:
      labels:
        app: ksubscriber
    spec:
      containers:
        - name: ksubscriber
          image: localhost:5000/nsubrahm/ksubscriber:v0.0.0
          env:
            - name: KAFKA_BROKER
              value: my-cluster-kafka-bootstrap:9092
            - name: KAFKA_TOPIC_NAME
              value: machine_data
          imagePullPolicy: Always
