version: '3.5'

services:
  subscriber:
    image: nsubrahm/subscriber:1.0
    build:
      dockerfile: Dockerfile
      context: ..
    env_file:
      - .env
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks