version: '3.5'

services:
  subscriber:
    container_name: subscriber
    image: nsubrahm/subscriber:v0.0.0
    env_file:
      - broker.env
      - sasl-auth.env
    networks:
      - kafkastreams-network

networks:
  kafkastreams-network:
    name: ks
